from enum import Enum


class EventType(Enum):
    CHANNEL_CREATED = "CHANNEL_CREATED"
    CHANNEL_UPDATED = "CHANNEL_UPDATED"
    CHANNEL_DELETED = "CHANNEL_DELETED"
    CONTENT_CREATED = "CONTENT_CREATED"
    CONTENT_UPDATED = "CONTENT_UPDATED"
    CONTENT_DELETED = "CONTENT_DELETED"
    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"
    USER_DELETED = "USER_DELETED"
