from enum import Enum


class SystemPermissionType(Enum):
    VIEW_SYSTEM_PERMISSIONS = "VIEW_SYSTEM_PERMISSIONS"
    UPDATE_SYSTEM_PERMISSIONS = "UPDATE_SYSTEM_PERMISSIONS"
    CREATE_CHANNEL = "CREATE_CHANNEL"
    CREATE_USER = "CREATE_USER"
    UPDATE_ANY_USER = "UPDATE_ANY_USER"
    DELETE_ANY_USER = "DELETE_ANY_USER"
